# ricemarch dfmc cms person management module
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8760

# datatsource
spring:
  application:
    name: cms-pms-service
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    # remote mysql
    #username: root
    #password: NEFU
    #url: jdbc:mysql://test.ricemarch.com:3306/cms_pms?serverTimeZone=GMT%2B8

    # local mysql
    #username: root
    #password: root
    #url: jdbc:mysql://localhost:3306/cms_pms?serverTimezone=Asia/Shanghai

    # remote postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
#    password: NEFU
    url: jdbc:postgresql://127.0.0.1:5432/cms_pms_pg
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 DruidDataSource作为数据源
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 80
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 1 from user_pg
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      keep-alive: true



  profiles:
    active: dev
#mybatis-plus

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:com/ricemarch/cms/pms/mapper/xml/*.xml
#target/classes/com/ricemarch/cms/pms/mapper/xml

#
cms:
  secretKey: R28K42ZEJ8LWRHU5
  salt: d343e10141f34276

logging:
  level:
    root: warn
    com.ricemarch: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
