# ricemarch dfmc cms person management module
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8760

# datatsource
spring:
  application:
    name: cms-pms-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: NEFU
    #password: root
    url: jdbc:mysql://test.ricemarch.com:3306/cms_pms?serverTimeZone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/cms_pms?serverTimezone=Asia/Shanghai
  profiles:
    active: dev
#mybatis-plus

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker


#
cms:
  secretKey: R28K42ZEJ8LWRHU5
  salt: d343e10141f34276

logging:
  level:
    root: warn
    com.ricemarch: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
